const articles = [
  {
    category: "高齢者レク",
    title: "吹きゴマ",
    publishedAt: "2021-11-30",
    description: "吹きゴマ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "6cphKY7OCgg",
  },
  {
    category: "高齢者レク",
    title: "サイコロゲーム",
    publishedAt: "2021-11-02",
    description: "サイコロゲーム",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "ZrVziivbOfU",
  },
  {
    category: "高齢者レク",
    title: "拍手で脳トレ",
    publishedAt: "2021-11-02",
    description: "拍手で脳トレ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "sL2Daqia2a0",
  },
  {
    category: "高齢者レク",
    title: "指折りグーパー",
    publishedAt: "2021-11-02",
    description: "指折りグーパー",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "X_HUXD-NJ-M",
  },
  {
    category: "高齢者レク",
    title: "たんぽぽのびんづめ",
    publishedAt: "2021-11-02",
    description: "たんぽぽのびんづめ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "UIT3HRQR8E0",
  },
  {
    category: "高齢者レク",
    title: "紙コップピンポン",
    publishedAt: "2021-11-02",
    description: "紙コップピンポン",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "VyFepbGPprk",
  },
  {
    category: "高齢者レク",
    title: "つま先かかと体操",
    publishedAt: "2021-11-02",
    description: "つま先かかと体操",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "-yiETmG_7Xk",
  },
  {
    category: "高齢者レク",
    title: "サイコロゲーム",
    publishedAt: "2021-10-04",
    description: "サイコロゲーム",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "XoYsjKDTamM",
  },
  {
    category: "高齢者レク",
    title: "あんたがたどこさでお手玉送り",
    publishedAt: "2021-10-04",
    description: "あんたがたどこさでお手玉送り",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "oGINLgsa_8Y",
  },
  {
    category: "高齢者レク",
    title: "お手玉ボウリング",
    publishedAt: "2021-10-04",
    description: "お手玉ボウリング",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "BTkUnR0HAb8",
  },
  {
    category: "高齢者レク",
    title: "ミミズの体操",
    publishedAt: "2021-09-02",
    description: "ミミズの体操",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "rFNnqLaSf7E",
  },
  {
    category: "高齢者レク",
    title: "お手玉ペタンク",
    publishedAt: "2021-08-30",
    description: "お手玉をつかってペタンク（的に近づける）をします。",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "vb_s-CmF2Wk",
  },
  {
    category: "高齢者レク",
    title: "チラシの折箱積み",
    publishedAt: "2021-08-30",
    description: "チラシの折箱を何個積むことができるかに挑戦",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "eK0mILRx85c",
  },
  {
    category: "高齢者レク",
    title: "オールインボール",
    publishedAt: "2021-08-30",
    description: "協力して穴からボールが全部落ちるようにします。",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "S14OBikJng0",
  },
  {
    category: "高齢者レク",
    title: "数字パズル",
    publishedAt: "2021-08-30",
    description: "お題の答えを数字パズルでつくります",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "MMmNKPjj4_g",
  },
  {
    category: "高齢者レク",
    title: "都道府県スリーヒントビンゴ",
    publishedAt: "2021-08-30",
    description: "3つのヒントから都道府県を当てます",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "uC5NC0b8uO4",
  },
  {
    category: "高齢者レク",
    title: "ぱかぱかゲーム",
    publishedAt: "2021-06-28",
    description: "ぱかぱかゲーム",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "jwnBT47xitI",
  },
  {
    category: "高齢者レク",
    title: "指折り体操",
    publishedAt: "2021-06-28",
    description: "指折り体操",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "7MQfTresAWg",
  },
  {
    category: "高齢者レク",
    title: "タクスポ　ボトルつかみ",
    publishedAt: "2021-06-28",
    description: "タクスポ　ボトルつかみ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "ZWEPE8FnbfQ",
  },
  {
    category: "高齢者レク",
    title: "パタカラを使ったレクリエーション①",
    publishedAt: "2021-06-25",
    description: "パタカラを使ったレクリエーション①",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "0z9-YBy9H80",
  },
  {
    category: "高齢者レク",
    title: "親指出し入れ体操",
    publishedAt: "2021-06-25",
    description: "親指出し入れ体操",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "PE9NEdjG-tA",
  },
  {
    category: "高齢者レク",
    title: "タクスポお尻歩き",
    publishedAt: "2021-06-25",
    description: "タクスポお尻歩き",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "zEDIToXPNes",
  },
  {
    category: "高齢者レク",
    title: "お手玉ふたつ",
    publishedAt: "2021-06-19",
    description: "お手玉を使ったレクリエーション活動を紹介します",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "KQ-9MUUfr-E",
  },
  {
    category: "高齢者レク",
    title: "パタカラ口腔体操",
    publishedAt: "2021-05-19",
    description: "パタカラ口腔体操",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "lXjnve_hEQM",
  },
  {
    category: "高齢者レク",
    title: "指折りワンとニャン",
    publishedAt: "2021-04-25",
    description: "指折りワンとニャン",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Cg2V4r4zTVs",
  },
  {
    category: "高齢者レク",
    title: "グーチョキパー体操",
    publishedAt: "2021-04-25",
    description: "グーチョキタイソウ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "l4z1eHfBswU",
  },
  {
    category: "高齢者レク",
    title: "グーパー",
    publishedAt: "2020-11-06",
    description: "グーパー",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①左手をパーにしながら前に突き出し、右手はグーにしながら胸に引き寄せる。\n②教師の「セーノ」の合図で、子どもは「ヨイショ」と一斉にかけ声をかけながら、左右の手を入れ替える。\n（前に突き出す手がパー、胸に引き寄せた手がグー）\n③合図のタイミングを徐々に速くしながら連続して行う。\n④次に、突き出す手をグー、胸に引き寄せる手をパーに変えて同様に行う。\n⑤さらに、左右の手を入れ替える時に拍手を加えて行うと難易度が上がる。",
    youtubeId: "0rtBmgTt2G8",
  },
  {
    category: "高齢者レク",
    title: "ラダーゲッター",
    publishedAt: "2020-11-06",
    description: "ラダーゲッター",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "B_3NvNY8P6o",
  },
  {
    category: "高齢者レク",
    title: "スキヤキジャンケン",
    publishedAt: "2020-11-06",
    description: "スキヤキジャンケン",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①数人でグループをつくり、家族の配役を決める。（お父さん、お母さん、お兄さんなど、全グループ同じ配役）\n②教師は、各家族のお父さんとジャンケンを行う。\n③教師に勝ったお父さんは、教師の持つ袋の中からカードを1枚引くことができる。\n④同様に、他の家族メンバーも順番にジャンケンをして、勝ったらカードを引いていく。\n⑤スキヤキの材料カード（5種類）を早くそろえたグループの勝ちとなる。",
    youtubeId: "ut_icXyaXfE",
  },
  {
    category: "介護予防レク",
    title: "バランススティックチャレンジ",
    publishedAt: "2022-04-07",
    description: "バランススティックチャレンジ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "4BRCUOdIY0A",
  },
  {
    category: "介護予防レク",
    title: "パスチャレ",
    publishedAt: "2022-04-07",
    description: "パスチャレ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "2s97nOgt6Bk",
  },
  {
    category: "介護予防レク",
    title: "ビー玉カーリング",
    publishedAt: "2021-11-30",
    description: "ビー玉カーリング",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "0ZpJMbWf9L4",
  },
  {
    category: "介護予防レク",
    title: "名前のダンス",
    publishedAt: "2021-11-30",
    description: "名前のダンス",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "xFbJ5lJLmvk",
  },
  {
    category: "介護予防レク",
    title: "サイコロゲーム",
    publishedAt: "2021-11-02",
    description: "サイコロゲーム",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "ZrVziivbOfU",
  },
  {
    category: "介護予防レク",
    title: "拍手で脳トレ",
    publishedAt: "2021-11-02",
    description: "拍手で脳トレ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "sL2Daqia2a0",
  },
  {
    category: "介護予防レク",
    title: "指折りグーパー",
    publishedAt: "2021-11-02",
    description: "指折りグーパー",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "X_HUXD-NJ-M",
  },
  {
    category: "介護予防レク",
    title: "たんぽぽのびんづめ",
    publishedAt: "2021-11-02",
    description: "たんぽぽのびんづめ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "UIT3HRQR8E0",
  },
  {
    category: "介護予防レク",
    title: "紙コップピンポン",
    publishedAt: "2021-11-02",
    description: "紙コップピンポン",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "VyFepbGPprk",
  },
  {
    category: "介護予防レク",
    title: "つま先かかと体操",
    publishedAt: "2021-11-02",
    description: "つま先かかと体操",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "-yiETmG_7Xk",
  },
  {
    category: "介護予防レク",
    title: "サイコロゲーム",
    publishedAt: "2021-10-04",
    description: "サイコロゲーム",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "XoYsjKDTamM",
  },
  {
    category: "介護予防レク",
    title: "紙ペラ体操",
    publishedAt: "2021-10-04",
    description: "紙ペラ体操",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "b0UCTdCCqBA",
  },
  {
    category: "介護予防レク",
    title: "あんたがたどこさでお手玉送り",
    publishedAt: "2021-10-04",
    description: "あんたがたどこさでお手玉送り",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "oGINLgsa_8Y",
  },
  {
    category: "介護予防レク",
    title: "お手玉ボウリング",
    publishedAt: "2021-10-04",
    description: "お手玉ボウリング",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "BTkUnR0HAb8",
  },
  {
    category: "介護予防レク",
    title: "脳トレグーチョキパー",
    publishedAt: "2021-10-04",
    description: "脳トレグーチョキパー体操",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "g5h1SzmqRB8",
  },
  {
    category: "介護予防レク",
    title: "ミミズの体操",
    publishedAt: "2021-09-02",
    description: "ミミズの体操",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "rFNnqLaSf7E",
  },
  {
    category: "介護予防レク",
    title: "お手玉ペタンク",
    publishedAt: "2021-08-30",
    description: "お手玉をつかってペタンク（的に近づける）をします。",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "vb_s-CmF2Wk",
  },
  {
    category: "介護予防レク",
    title: "チラシの折箱積み",
    publishedAt: "2021-08-30",
    description: "チラシの折箱を何個積むことができるかに挑戦",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "eK0mILRx85c",
  },
  {
    category: "介護予防レク",
    title: "キーボードタッチ",
    publishedAt: "2021-08-30",
    description: "指示された数字をタッチします",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "SqANUJu2hLc",
  },
  {
    category: "介護予防レク",
    title: "くるましょうぎ",
    publishedAt: "2021-08-30",
    description: "くるましょうぎ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "E4nRAbe4cIQ",
  },
  {
    category: "介護予防レク",
    title: "テッシュ引き",
    publishedAt: "2021-08-30",
    description: "ペットボトルが倒れないようにテッシュを引きます。",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "5ry96vDf7zs",
  },
  {
    category: "介護予防レク",
    title: "オールインボール",
    publishedAt: "2021-08-30",
    description: "協力して穴からボールが全部落ちるようにします。",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "S14OBikJng0",
  },
  {
    category: "介護予防レク",
    title: "数字パズル",
    publishedAt: "2021-08-30",
    description: "お題の答えを数字パズルでつくります",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "MMmNKPjj4_g",
  },
  {
    category: "介護予防レク",
    title: "都道府県スリーヒントビンゴ",
    publishedAt: "2021-08-30",
    description: "3つのヒントから都道府県を当てます",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "uC5NC0b8uO4",
  },
  {
    category: "介護予防レク",
    title: "エアー縄跳び体操",
    publishedAt: "2021-08-30",
    description: "実際の縄跳びはしないで縄とびの動きを楽しむ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "RmDXt7bjv8k",
  },
  {
    category: "介護予防レク",
    title: "キャップカーリング",
    publishedAt: "2021-08-03",
    description: "キャップカーリング",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Y73BpcUGsyM",
  },
  {
    category: "介護予防レク",
    title: "ペットボトルキャップジャンプ",
    publishedAt: "2021-08-03",
    description: "ペットボトルキャップジャンプ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "I-FCpfZCzvI",
  },
  {
    category: "介護予防レク",
    title: "指折り体操",
    publishedAt: "2021-06-28",
    description: "指折り体操",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "7MQfTresAWg",
  },
  {
    category: "介護予防レク",
    title: "ぱかぱかゲーム",
    publishedAt: "2021-06-28",
    description: "ぱかぱかゲーム",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "jwnBT47xitI",
  },
  {
    category: "介護予防レク",
    title: "タクスポ　ボトルつかみ",
    publishedAt: "2021-06-28",
    description: "タクスポ　ボトルつかみ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "ZWEPE8FnbfQ",
  },
  {
    category: "介護予防レク",
    title: "パタカラを使ったレクリエーション②",
    publishedAt: "2021-06-28",
    description: "パタカラを使ったレクリエーション②",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "RgwvtalZiMQ",
  },
  {
    category: "介護予防レク",
    title: "親指出し入れ体操",
    publishedAt: "2021-06-25",
    description: "親指出し入れ体操",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "PE9NEdjG-tA",
  },
  {
    category: "介護予防レク",
    title: "タクスポお尻歩き",
    publishedAt: "2021-06-25",
    description: "タクスポお尻歩き",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "zEDIToXPNes",
  },
  {
    category: "介護予防レク",
    title: "パタカラを使ったレクリエーション①",
    publishedAt: "2021-06-25",
    description: "パタカラを使ったレクリエーション①",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "0z9-YBy9H80",
  },
  {
    category: "介護予防レク",
    title: "お手玉ふたつ",
    publishedAt: "2021-06-19",
    description: "お手玉を使ったレクリエーション活動を紹介します",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "KQ-9MUUfr-E",
  },
  {
    category: "介護予防レク",
    title: "サイコロ21",
    publishedAt: "2021-06-07",
    description:
      "オリジナル！おうちで60秒チャレンジ！\n\r\n「サイコロ21」です。\n\r\n3人それぞれ蹴って出た目の合計が21になる時間を競います。",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "jynFecYGhH8",
  },
  {
    category: "介護予防レク",
    title: "パタカラ口腔体操",
    publishedAt: "2021-05-19",
    description: "パタカラ口腔体操",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "lXjnve_hEQM",
  },
  {
    category: "介護予防レク",
    title: "指折りワンとニャン",
    publishedAt: "2021-04-25",
    description: "指折りワンとニャン",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Cg2V4r4zTVs",
  },
  {
    category: "介護予防レク",
    title: "グーチョキパー体操",
    publishedAt: "2021-04-25",
    description: "グーチョキタイソウ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "l4z1eHfBswU",
  },
  {
    category: "介護予防レク",
    title: "指折りグーパー",
    publishedAt: "2020-12-23",
    description: "指折りグーパー",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "tRRWRD__TZk",
  },
  {
    category: "介護予防レク",
    title: "フワフワシュート",
    publishedAt: "2020-11-25",
    description: "フワフワシュート",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "B2t2IOzOzGU",
  },
  {
    category: "介護予防レク",
    title: "風力マッスルアップ",
    publishedAt: "2020-11-25",
    description: "風力マッスルアップ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "i4J0TJE1738",
  },
  {
    category: "介護予防レク",
    title: "ボールストン",
    publishedAt: "2020-11-25",
    description: "ボールストン",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "wk2C1ePMst4",
  },
  {
    category: "介護予防レク",
    title: "2拍子3拍子",
    publishedAt: "2020-11-06",
    description: "2拍子3拍子",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①片方の手で2拍子、もう一方の手で3拍子の動作を、左右同時に行う。\n2拍子：腕を上下に動かす。\n3拍子：腕を上から下、横、もとの位置へと、三角形を描くように動かす。\n②3拍子の歌を歌いながら、動作を同時に続けることに挑戦する。",
    youtubeId: "p6E_Jp-bV1E",
  },
  {
    category: "介護予防レク",
    title: "後出しジャンケン",
    publishedAt: "2020-11-06",
    description: "後出しジャンケン",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①教師の「ジャンケンポン」に続いて、子どもは「ポン」と応えながら教師とあいこになるように出す。（教師のポンのあとに子どものポンが続き、「ジャンケンポン・ポン」となるように）\n②かけ声のタイミングを徐々に速くしながら連続して行う。（2回目以降はかけ声を「ポン（教師）・ポン（子ども）」とテンポよく続くようにする）\n③同様の手順で、子どもが勝つように出す、負けるように出す、と難易度を上げて展開していく。",
    youtubeId: "CWbI_wJbiIM",
  },
  {
    category: "介護予防レク",
    title: "協調グーパー",
    publishedAt: "2020-11-06",
    description: "協調グーパー",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①2人組になって向かい合い、お互いに右手をグー、左手をパーにして相手の前に出し、相手の手のひらにグーを乗せる。\n②教師の合図で、グーとパーを入れ替える。\n③慣れてきたら、入れ替える時に拍手を加える。\n④これを歌に合わせて続けて行う。",
    youtubeId: "n5tjnqnPtfE",
  },
  {
    category: "介護予防レク",
    title: "弟子のジャンケン",
    publishedAt: "2020-11-06",
    description: "弟子のジャンケン",
    numOfPlayers: "2人から",
    howLong: "--",
    detail:
      "①2人組になって向かい合い、「弟子、弟子、弟子」と声をかけながら、3度目の「弟子」でジャンケンをする。あいこの場合は、続けて「弟子」と言ってジャンケンをして、勝負が決まるまで続ける。\n②ジャンケンで勝負が決まったら、次の言葉と動作をお互い同時に行う。\n勝った人：「あなたは私の弟子」と言いながら、「あなたは」で両手を前に出し、「私の」で両手を胸に付ける動作をし、「弟子」で次のジャンケンをする。\n負けた人：「私はあなたの弟子」と言いながら、「私は」で両手を胸につけ、「あなたの」で両手を前に出す動作をし、「弟子」で次のジャンケンをする。\n③お互いが言葉と動作を間違えず、長く続けられるように協力する。",
    youtubeId: "6ojHLhPaxwA",
  },
  {
    category: "介護予防レク",
    title: "リレーポエム",
    publishedAt: "2020-11-06",
    description: "リレーポエム",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①４人程度のグループをつくり、バラバラに座る。\n②詩のテーマを発表する。（季節など）\n③グループのメンバー１人ずつの言葉をつないで、テーマに合ったひとつの詩を完成させることを伝える。\n④最初の人がまず、テーマに合った短い言葉を書く。（桜舞う、や新緑が、\nなど）\n⑤一定時間経ったら支援者が合図を出し、次の対象者へ紙を回す。\n⑥紙が回ってきた対象者は、書かれている言葉につながる言葉を考えて書き、合図があったら次へ回す。\n⑦あらかじめ決めておいた回数を回し終えたら終了。\n⑧どんな詩が完成したか発表する。",
    youtubeId: "9MFDdpV0x6o",
  },
  {
    category: "介護予防レク",
    title: "マンカラ",
    publishedAt: "2020-11-06",
    description: "マンカラ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "w9joCK5PCpk",
  },
  {
    category: "介護予防レク",
    title: "ラダーゲッター",
    publishedAt: "2020-11-06",
    description: "ラダーゲッター",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "B_3NvNY8P6o",
  },
  {
    category: "介護予防レク",
    title: "キャッチング・ザ・スティック",
    publishedAt: "2020-11-06",
    description: "キャッチング・ザ・スティック",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "XYnEJxHmPcE",
  },
  {
    category: "介護予防レク",
    title: "ネット・パス・ラリー",
    publishedAt: "2020-11-06",
    description: "ネット・パス・ラリー",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "hZ7wmMaUFRQ",
  },
  {
    category: "介護予防レク",
    title: "ニチレクボール・チャレンジ",
    publishedAt: "2020-11-06",
    description: "ニチレクボール・チャレンジ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "0aiaVw9ioAo",
  },
  {
    category: "介護予防レク",
    title: "スピード・ラダーゲッター",
    publishedAt: "2020-11-06",
    description: "スピード・ラダーゲッター",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Wi7d0AS9u9s",
  },
  {
    category: "介護予防レク",
    title: "グーパー",
    publishedAt: "2020-11-06",
    description: "グーパー",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①左手をパーにしながら前に突き出し、右手はグーにしながら胸に引き寄せる。\n②教師の「セーノ」の合図で、子どもは「ヨイショ」と一斉にかけ声をかけながら、左右の手を入れ替える。\n（前に突き出す手がパー、胸に引き寄せた手がグー）\n③合図のタイミングを徐々に速くしながら連続して行う。\n④次に、突き出す手をグー、胸に引き寄せる手をパーに変えて同様に行う。\n⑤さらに、左右の手を入れ替える時に拍手を加えて行うと難易度が上がる。",
    youtubeId: "0rtBmgTt2G8",
  },
  {
    category: "介護予防レク",
    title: "2拍子3拍子",
    publishedAt: "2020-11-06",
    description: "2拍子3拍子",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①片方の手で2拍子、もう一方の手で3拍子の動作を、左右同時に行う。\n2拍子：腕を上下に動かす。\n3拍子：腕を上から下、横、もとの位置へと、三角形を描くように動かす。\n②3拍子の歌を歌いながら、動作を同時に続けることに挑戦する。",
    youtubeId: "p6E_Jp-bV1E",
  },
  {
    category: "介護予防レク",
    title: "ラダーゲッター",
    publishedAt: "2020-11-06",
    description: "ラダーゲッター",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "B_3NvNY8P6o",
  },
  {
    category: "介護予防レク",
    title: "茶つぼ",
    publishedAt: "2020-11-06",
    description: "茶つぼ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "NJjtnX4mi2Q",
  },
  {
    category: "介護予防レク",
    title: "指相撲",
    publishedAt: "2020-11-06",
    description: "指相撲",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "MZDIVlq_s9s",
  },
  {
    category: "介護予防レク",
    title: "あんたがたどこさ",
    publishedAt: "2020-11-06",
    description: "あんたがたどこさ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "oU_wUgpaAnk",
  },
  {
    category: "介護予防レク",
    title: "スポーツテンカ",
    publishedAt: "2020-11-06",
    description: "スポーツテンカ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "X7z9VXGyyIo",
  },
  {
    category: "介護予防レク",
    title: "マンカラ",
    publishedAt: "2020-11-06",
    description: "マンカラ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "w9joCK5PCpk",
  },
  {
    category: "介護予防レク",
    title: "リズム肩たたき",
    publishedAt: "2020-11-06",
    description: "リズム肩たたき",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①4拍子の歌を歌いながら、右手で左の肩を8回、左手で右の肩を8回、繰り返したたき、リズムをとる。\n②慣れてきたら、たたく回数を、左右8回、左右4回、左右2回、左右1回、拍手1回と変化させる。リズムに合わせた肩たたきが揃うことで、一体感と達成感をつくる。",
    youtubeId: "SC6adK_pCp4",
  },
  {
    category: "介護予防レク",
    title: "キャッチング・ザ・スティック",
    publishedAt: "2020-11-06",
    description: "キャッチング・ザ・スティック",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "XYnEJxHmPcE",
  },
  {
    category: "介護予防レク",
    title: "ネット・パス・ラリー",
    publishedAt: "2020-11-06",
    description: "ネット・パス・ラリー",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "hZ7wmMaUFRQ",
  },
  {
    category: "介護予防レク",
    title: "ニチレクボール・チャレンジ",
    publishedAt: "2020-11-06",
    description: "ニチレクボール・チャレンジ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "0aiaVw9ioAo",
  },
  {
    category: "介護予防レク",
    title: "スピード・ラダーゲッター",
    publishedAt: "2020-11-06",
    description: "スピード・ラダーゲッター",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Wi7d0AS9u9s",
  },
  {
    category: "介護予防レク",
    title: "リズム手合わせ",
    publishedAt: "2020-11-06",
    description: "リズム手合わせ",
    numOfPlayers: "2人から6人まで",
    howLong: "--",
    detail:
      "①2人組になって向かい合い、3拍子の歌を歌いながら次の動作を続ける。\nａ両手で膝をたたく→ｂ胸の前で拍手→ｃ両手を前に出し互いの手のひらを合わせる\n②4人組（①の2人組が2組）になり、対角に向かい合う。①と同様の動作をする2人組と、ｂ→ｃ→ａの動作をする2人組にわけ、3拍子の歌を歌いながら同時に動作を続ける。\n③6人組（①の2人組が3組）になり、対角に向かい合う。②の動作に加え、ｃ→ａ→ｂの動作をする2人組を決め、3拍子の歌を歌いながら同時に動作を続ける。",
    youtubeId: "TWqXoIC6q4o",
  },
  {
    category: "介護予防レク",
    title: "リズム手合わせ",
    publishedAt: "2020-11-06",
    description: "リズム手合わせ",
    numOfPlayers: "2人から6人まで",
    howLong: "--",
    detail:
      "①2人組になって向かい合い、3拍子の歌を歌いながら次の動作を続ける。\nａ両手で膝をたたく→ｂ胸の前で拍手→ｃ両手を前に出し互いの手のひらを合わせる\n②4人組（①の2人組が2組）になり、対角に向かい合う。①と同様の動作をする2人組と、ｂ→ｃ→ａの動作をする2人組にわけ、3拍子の歌を歌いながら同時に動作を続ける。\n③6人組（①の2人組が3組）になり、対角に向かい合う。②の動作に加え、ｃ→ａ→ｂの動作をする2人組を決め、3拍子の歌を歌いながら同時に動作を続ける。",
    youtubeId: "TWqXoIC6q4o",
  },
  {
    category: "学校レク",
    title: "ひざポンチャレンジ",
    publishedAt: "2022-04-07",
    description:
      "二人が向き合い、あたま・かた・ひざぽんの歌に合わせて体を動かすゲームです。",
    numOfPlayers: "2人",
    howLong: "--",
    detail:
      "①二人が向かい合ってスタンバイします。\n②あたま・かた・ひざ、の歌詞に合わせて、それぞれの部位をタッチします。ぽんのときは、お互いの両手を合わせましょう。\n③め・みみ・はな・くちも、歌詞に合わせて、それぞれの部位をタッチします。\n④２回目は背中合わせになって行います。\n⑤あたま・かた・ひざ、の歌詞に合わせて、それぞれの部位をタッチします。ぽんのときは、股の下からお互いの両手を合わせましょう。\n⑥３回目は、ボールを使います。\n⑦あたま・かた・ひざ、の歌詞に合わせて、それぞれの部位からボールを受け渡します。ひざのときは、股の下からボールを受け渡しましょう。\n⑧最後は、にっこりピースサインでポーズ！",
    youtubeId: "1NWYu28Fw9I",
  },
  {
    category: "学校レク",
    title: "パスレクリエーション",
    publishedAt: "2022-04-07",
    description: "心をつなげ！パスレクリエーション",
    numOfPlayers: "5人",
    howLong: "--",
    detail:
      "①難易度☆\n円になってボールを高い位置でキャッチし、パスをします。そのとき、パスする人の名前を呼びましょう。\n②難易度☆☆\n円になってオーバーパスをします。\n③難易度☆☆☆☆\n円になってボール２個で一方向に向かってオーバーパスをします。パスするときは、もう一人パスする人と高さとタイミングを合わせましょう。\n④難易度☆☆☆☆\n一列に並んで全員正面を向きます。右からくるボールを90度回転しながら左へパスをします。\n⑤難易度☆☆☆☆\n一列になり、高い位置でキャッチし、後ろにパスします。\n⑥難易度☆☆☆☆☆\n一列になり、後ろにオーバーパスをします。\n⑦難易度☆☆☆☆☆☆☆\n一列になり、後ろにジャンプしてオーバーパスをします。",
    youtubeId: "PafVVXpHxgA",
  },
  {
    category: "学校レク",
    title: "バランススティックチャレンジ",
    publishedAt: "2022-04-07",
    description: "バランススティックチャレンジ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "4BRCUOdIY0A",
  },
  {
    category: "学校レク",
    title: "パスチャレ",
    publishedAt: "2022-04-07",
    description: "パスチャレ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "2s97nOgt6Bk",
  },
  {
    category: "学校レク",
    title: "吹きゴマ",
    publishedAt: "2021-11-30",
    description: "吹きゴマ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "6cphKY7OCgg",
  },
  {
    category: "学校レク",
    title: "ビー玉カーリング",
    publishedAt: "2021-11-30",
    description: "ビー玉カーリング",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "0ZpJMbWf9L4",
  },
  {
    category: "学校レク",
    title: "いいなりゲーム",
    publishedAt: "2021-11-30",
    description: "いいなりゲーム",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "KfbLNLw3wqE",
  },
  {
    category: "学校レク",
    title: "あっち向いてホイ",
    publishedAt: "2021-11-30",
    description: "あっち向いてホイ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "jT1Qu6z7YvY",
  },
  {
    category: "学校レク",
    title: "名前のダンス",
    publishedAt: "2021-11-30",
    description: "名前のダンス",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "xFbJ5lJLmvk",
  },
  {
    category: "学校レク",
    title: "サイコロゲーム",
    publishedAt: "2021-11-02",
    description: "サイコロゲーム",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "ZrVziivbOfU",
  },
  {
    category: "学校レク",
    title: "たんぽぽのびんづめ",
    publishedAt: "2021-11-02",
    description: "たんぽぽのびんづめ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "UIT3HRQR8E0",
  },
  {
    category: "学校レク",
    title: "紙コップピンポン",
    publishedAt: "2021-11-02",
    description: "紙コップピンポン",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "VyFepbGPprk",
  },
  {
    category: "学校レク",
    title: "メンコあそび",
    publishedAt: "2021-10-04",
    description: "メンコあそび",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "QVrNIroS38E",
  },
  {
    category: "学校レク",
    title: "ゴロゴロジャンプ",
    publishedAt: "2021-10-04",
    description: "ゴロゴロジャンプ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "_stjQIIbtCw",
  },
  {
    category: "学校レク",
    title: "サイコロゲーム",
    publishedAt: "2021-10-04",
    description: "サイコロゲーム",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "XoYsjKDTamM",
  },
  {
    category: "学校レク",
    title: "さんならべ",
    publishedAt: "2021-10-04",
    description: "さんならべ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "8yEDVPpYyXQ",
  },
  {
    category: "学校レク",
    title: "ひもあそび　その2",
    publishedAt: "2021-10-04",
    description: "ひもあそび　その2",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Uq4sBfsrAXo",
  },
  {
    category: "学校レク",
    title: "よしお兄さんとうたおう！『うみ』",
    publishedAt: "2021-08-30",
    description: "よしお兄さんとうたおう！『うみ』",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Bqzc0cBF0c4",
  },
  {
    category: "学校レク",
    title: "コロコロストップ",
    publishedAt: "2021-08-30",
    description: "ボールを指定の場所に止まるように転がします",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Mt-KBV6YfIc",
  },
  {
    category: "学校レク",
    title: "お手玉ペタンク",
    publishedAt: "2021-08-30",
    description: "お手玉をつかってペタンク（的に近づける）をします。",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "vb_s-CmF2Wk",
  },
  {
    category: "学校レク",
    title: "キーボードタッチ",
    publishedAt: "2021-08-30",
    description: "指示された数字をタッチします",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "SqANUJu2hLc",
  },
  {
    category: "学校レク",
    title: "くるましょうぎ",
    publishedAt: "2021-08-30",
    description: "くるましょうぎ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "E4nRAbe4cIQ",
  },
  {
    category: "学校レク",
    title: "テッシュ引き",
    publishedAt: "2021-08-30",
    description: "ペットボトルが倒れないようにテッシュを引きます。",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "5ry96vDf7zs",
  },
  {
    category: "学校レク",
    title: "ひもあそび",
    publishedAt: "2021-08-30",
    description: "ひもであそび",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "GLS3o3imksQ",
  },
  {
    category: "学校レク",
    title: "ザリガニジャンケン",
    publishedAt: "2021-08-03",
    description: "ザリガニジャンケン",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "RYoEbHiSOKw",
  },
  {
    category: "学校レク",
    title: "いろいろジャンケン",
    publishedAt: "2021-08-03",
    description: "いろいろジャンケン",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "LkRLOuGP4IY",
  },
  {
    category: "学校レク",
    title: "おうちで60秒チャレンジ",
    publishedAt: "2021-08-03",
    description: "おうちで60秒チャレンジ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "ntQUW2_mUug",
  },
  {
    category: "学校レク",
    title: "キャップカーリング",
    publishedAt: "2021-08-03",
    description: "キャップカーリング",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Y73BpcUGsyM",
  },
  {
    category: "学校レク",
    title: "くるくる紙コップ",
    publishedAt: "2021-06-07",
    description: "紙コップがくるくる回転して飛びます",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "V_u9oTnCsCg",
  },
  {
    category: "学校レク",
    title: "だるまさんが転んだ",
    publishedAt: "2021-05-19",
    description: "だるまさんが転んだ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "ZHM8f2AEv6w",
  },
  {
    category: "学校レク",
    title: "パスパスチャレンジ",
    publishedAt: "2021-04-25",
    description: "パスパスチャレンジ",
    numOfPlayers: "2人から",
    howLong: "--",
    youtubeId: "Zt-MRD3zXlQ",
  },
  {
    category: "学校レク",
    title: "パンパンパスチャレンジ",
    publishedAt: "2020-12-23",
    description: "パンパンパスチャレンジ",
    numOfPlayers: "2人から",
    howLong: "1分",
    detail:
      "詳しくはこちらでご確認ください。\nhttps://www.recreation.jp/challenge/article/719",
    youtubeId: "xTMTWFY7Nvw",
  },
  {
    category: "学校レク",
    title: "指折りグーパー",
    publishedAt: "2020-12-23",
    description: "指折りグーパー",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "tRRWRD__TZk",
  },
  {
    category: "学校レク",
    title: "リズム手合わせ",
    publishedAt: "2020-11-06",
    description: "リズム手合わせ",
    numOfPlayers: "2人から6人まで",
    howLong: "--",
    detail:
      "①2人組になって向かい合い、3拍子の歌を歌いながら次の動作を続ける。\nａ両手で膝をたたく→ｂ胸の前で拍手→ｃ両手を前に出し互いの手のひらを合わせる\n②4人組（①の2人組が2組）になり、対角に向かい合う。①と同様の動作をする2人組と、ｂ→ｃ→ａの動作をする2人組にわけ、3拍子の歌を歌いながら同時に動作を続ける。\n③6人組（①の2人組が3組）になり、対角に向かい合う。②の動作に加え、ｃ→ａ→ｂの動作をする2人組を決め、3拍子の歌を歌いながら同時に動作を続ける。",
    youtubeId: "TWqXoIC6q4o",
  },
  {
    category: "学校レク",
    title: "2拍子3拍子",
    publishedAt: "2020-11-06",
    description: "2拍子3拍子",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①片方の手で2拍子、もう一方の手で3拍子の動作を、左右同時に行う。\n2拍子：腕を上下に動かす。\n3拍子：腕を上から下、横、もとの位置へと、三角形を描くように動かす。\n②3拍子の歌を歌いながら、動作を同時に続けることに挑戦する。",
    youtubeId: "p6E_Jp-bV1E",
  },
  {
    category: "学校レク",
    title: "チクタクボンボン",
    publishedAt: "2020-11-06",
    description: "チクタクボンボン",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①数人でグループをつくり円になる。時計の針をイメージして時計回りに1人ずつ、チク・タク・チク・タクと言う。1時の場合はチク・タク・チク・タクに続いて「ボーン」と1回、2時の場合は、チク・タク・チク・タクに続いて「ボーン・ボーン」と2回時報を打つ。（時報は1人ひとつずつ打つ）\n②どのグループがどこまで正確に時報を打つことができるか、グループで協力して競う。",
    youtubeId: "JRAuRN230J8",
  },
  {
    category: "学校レク",
    title: "王冠とり",
    publishedAt: "2020-11-06",
    description: "王冠とり",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①数人でグループをつくり、相談をして王様または王女様を決める。\n②各グループでジャンケンに出ていく順番を決める。（王様は最後）\n③各グループの1番目の対象者が出てきてジャンケンをし、負けた対象者から順に列をつくる。\n④一番前の対象者と次の対象者がジャンケンをし、勝てば残って次のグループの対象者とジャンケンをする。負けたら自分のグループに戻り、2番目の対象者を列の最後尾へ送り出す。\n⑤続けて行い、最後まで王様の残っていたグループが勝ちとなる。",
    youtubeId: "IQnElEVoebc",
  },
  {
    category: "学校レク",
    title: "ステレオコール",
    publishedAt: "2020-11-06",
    description: "ステレオコール",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①出題する子どもが前に出る。\n②答えとなる言葉を決める。（みかん、など）\n③出題者に一文字ずつ割り当てる。\n④出題者が自分に割り当てられた文字を一斉に発声する。\n⑤他の子どもたちは解答者になって聞き分けて答える。",
    youtubeId: "26eG4LwjmLo",
  },
  {
    category: "学校レク",
    title: "リレーポエム",
    publishedAt: "2020-11-06",
    description: "リレーポエム",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①４人程度のグループをつくり、バラバラに座る。\n②詩のテーマを発表する。（季節など）\n③グループのメンバー１人ずつの言葉をつないで、テーマに合ったひとつの詩を完成させることを伝える。\n④最初の人がまず、テーマに合った短い言葉を書く。（桜舞う、や新緑が、\nなど）\n⑤一定時間経ったら支援者が合図を出し、次の対象者へ紙を回す。\n⑥紙が回ってきた対象者は、書かれている言葉につながる言葉を考えて書き、合図があったら次へ回す。\n⑦あらかじめ決めておいた回数を回し終えたら終了。\n⑧どんな詩が完成したか発表する。",
    youtubeId: "9MFDdpV0x6o",
  },
  {
    category: "学校レク",
    title: "リズム手合わせ",
    publishedAt: "2020-11-06",
    description: "リズム手合わせ",
    numOfPlayers: "2人から6人まで",
    howLong: "--",
    detail:
      "①2人組になって向かい合い、3拍子の歌を歌いながら次の動作を続ける。\nａ両手で膝をたたく→ｂ胸の前で拍手→ｃ両手を前に出し互いの手のひらを合わせる\n②4人組（①の2人組が2組）になり、対角に向かい合う。①と同様の動作をする2人組と、ｂ→ｃ→ａの動作をする2人組にわけ、3拍子の歌を歌いながら同時に動作を続ける。\n③6人組（①の2人組が3組）になり、対角に向かい合う。②の動作に加え、ｃ→ａ→ｂの動作をする2人組を決め、3拍子の歌を歌いながら同時に動作を続ける。",
    youtubeId: "TWqXoIC6q4o",
  },
  {
    category: "学校レク",
    title: "スピード・ラダーゲッター",
    publishedAt: "2020-11-06",
    description: "スピード・ラダーゲッター",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Wi7d0AS9u9s",
  },
  {
    category: "学校レク",
    title: "熊が出た",
    publishedAt: "2020-11-06",
    description: "熊が出た",
    numOfPlayers: "10人から",
    howLong: "--",
    detail:
      "①10人程度のグループをつくり、縦1列になる。\n②先頭の人が振り返って2番目の子に「熊が出た！」と大声で伝える。2番目の子は先頭の子に「エッー！」と大声で、びっくりして聞き返す。\n③もう一度先頭の子は、「熊が出た！」と伝える。2番目の子は熊が出たことを理解し、3番目の子に「熊が出た！」と伝える。3番目の子は2番目の子に「エッー！」と聞き返し、2番目の子は先頭の子に「エッー！」と伝える。\n④「熊が出た！」と1度聞いた時には「エッー！」と聞き返し、2度目以降聞いた時は後ろの子へ「熊が出た！」と伝えていく。先頭の人は「エッー！」が返ってくるたびに「熊が出た！」を繰り返すことになる。\n⑤「エッー！」の声は必ず先頭まで戻し、最後尾の子が2度目の「熊が出た！」を聞いたら、「大変だ！死んだふりをしろ！」と言って、チーム全体が死んだふりをする。どのチームがこの動作を早くできるかを競う。",
    youtubeId: "Bi7L8CseVdE",
  },
  {
    category: "学校レク",
    title: "スキヤキジャンケン",
    publishedAt: "2020-11-06",
    description: "スキヤキジャンケン",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①数人でグループをつくり、家族の配役を決める。（お父さん、お母さん、お兄さんなど、全グループ同じ配役）\n②教師は、各家族のお父さんとジャンケンを行う。\n③教師に勝ったお父さんは、教師の持つ袋の中からカードを1枚引くことができる。\n④同様に、他の家族メンバーも順番にジャンケンをして、勝ったらカードを引いていく。\n⑤スキヤキの材料カード（5種類）を早くそろえたグループの勝ちとなる。",
    youtubeId: "ut_icXyaXfE",
  },
  {
    category: "学校レク",
    title: "４人子分の大親分",
    publishedAt: "2020-11-06",
    description: "４人子分の大親分",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①それぞれ相手を見つけ2人でジャンケンをする。\n②勝った子どもは親分、負けた子どもは子分となって、親分の肩に手を乗せてつながる。\n③親分同士がジャンケンをし、負けた親分は勝った親分の子分となり最後尾につく。負けた親分についていた子分は親分となり、他の親分を探してジャンケンを行う。\n④親分同士がジャンケンをし、負けたら子分となる。負けた親分についていた子分は、先頭の子分が親分となり、続けていく。\n⑤ジャンケンに続けて勝ち、4人子分ができたら大親分となったらあがり。",
    youtubeId: "ml4DYfh3dLU",
  },
  {
    category: "学校レク",
    title: "そーれで拍手",
    publishedAt: "2020-11-06",
    description: "そーれで拍手",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①教師の「そーれ」の合図で子どもたちは拍手を1回行う。\n②続いての「そーれ」では2回、その次は3回、と連続して行いそのたびに数を増やしていく。\n③拍手が揃う心地よさを感じながら行い、教師が「そこまで」と言ったところの回数の人数でグループを作り座る。\n④数を変えて何度か行い、グループになるたびに自己紹介などをすると交流ができる。",
    youtubeId: "6VtvhMLvmAo",
  },
  {
    category: "学校レク",
    title: "だるまさん",
    publishedAt: "2020-11-06",
    description: "だるまさん",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①教師が「ダルマさん〇〇してください」と言った時だけ、子どもは言われた動作を行う。\n（「ダルマさん、右手を上げて下さい」と言われたら、子どもは右手を上げる）\n②“ダルマさん”という言葉がつかない時は、従ってはいけない。\n③教師は“ダルマさん”という言葉を入れたり、入れなかったりしてフェイントをかける。\nまた、多くの子の間違いを誘い、緊張を開放していく展開もある。",
    youtubeId: "c6YP1_Vu55Q",
  },
  {
    category: "学校レク",
    title: "スポーツテンカ必殺キャッチ技（スーパーキャッチ編）",
    publishedAt: "2020-11-06",
    description: "スポーツテンカ必殺キャッチ技（スーパーキャッチ編）",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "C3JH61S7T1Y",
  },
  {
    category: "学校レク",
    title: "ニチレクボール・チャレンジ",
    publishedAt: "2020-11-06",
    description: "ニチレクボール・チャレンジ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "0aiaVw9ioAo",
  },
  {
    category: "学校レク",
    title: "スポーツテンカ必殺キャッチ技（スーパーキャッチ編）",
    publishedAt: "2020-11-06",
    description: "スポーツテンカ必殺キャッチ技（スーパーキャッチ編）",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "C3JH61S7T1Y",
  },
  {
    category: "学校レク",
    title: "スポーツテンカ",
    publishedAt: "2020-11-06",
    description: "スポーツテンカ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "X7z9VXGyyIo",
  },
  {
    category: "学校レク",
    title: "マンカラ",
    publishedAt: "2020-11-06",
    description: "マンカラ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "w9joCK5PCpk",
  },
  {
    category: "学校レク",
    title: "ラダーゲッター",
    publishedAt: "2020-11-06",
    description: "ラダーゲッター",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "B_3NvNY8P6o",
  },
  {
    category: "学校レク",
    title: "キャッチング・ザ・スティック",
    publishedAt: "2020-11-06",
    description: "キャッチング・ザ・スティック",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "XYnEJxHmPcE",
  },
  {
    category: "学校レク",
    title: "5人10脚",
    publishedAt: "2020-11-06",
    description: "5人10脚",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "jI2IHEj1mDY",
  },
  {
    category: "学校レク",
    title: "ネット・パス・ラリー",
    publishedAt: "2020-11-06",
    description: "ネット・パス・ラリー",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "hZ7wmMaUFRQ",
  },
  {
    category: "学校レク",
    title: "リズム肩たたき",
    publishedAt: "2020-11-06",
    description: "リズム肩たたき",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①4拍子の歌を歌いながら、右手で左の肩を8回、左手で右の肩を8回、繰り返したたき、リズムをとる。\n②慣れてきたら、たたく回数を、左右8回、左右4回、左右2回、左右1回、拍手1回と変化させる。リズムに合わせた肩たたきが揃うことで、一体感と達成感をつくる。",
    youtubeId: "SC6adK_pCp4",
  },
  {
    category: "学校レク",
    title: "スピード・ラダーゲッター",
    publishedAt: "2020-11-06",
    description: "スピード・ラダーゲッター",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Wi7d0AS9u9s",
  },
  {
    category: "学校レク",
    title: "リズム手合わせ",
    publishedAt: "2020-11-06",
    description: "リズム手合わせ",
    numOfPlayers: "2人から6人まで",
    howLong: "--",
    detail:
      "①2人組になって向かい合い、3拍子の歌を歌いながら次の動作を続ける。\nａ両手で膝をたたく→ｂ胸の前で拍手→ｃ両手を前に出し互いの手のひらを合わせる\n②4人組（①の2人組が2組）になり、対角に向かい合う。①と同様の動作をする2人組と、ｂ→ｃ→ａの動作をする2人組にわけ、3拍子の歌を歌いながら同時に動作を続ける。\n③6人組（①の2人組が3組）になり、対角に向かい合う。②の動作に加え、ｃ→ａ→ｂの動作をする2人組を決め、3拍子の歌を歌いながら同時に動作を続ける。",
    youtubeId: "TWqXoIC6q4o",
  },
  {
    category: "学校レク",
    title: "リレーポエム",
    publishedAt: "2020-11-06",
    description: "リレーポエム",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①４人程度のグループをつくり、バラバラに座る。\n②詩のテーマを発表する。（季節など）\n③グループのメンバー１人ずつの言葉をつないで、テーマに合ったひとつの詩を完成させることを伝える。\n④最初の人がまず、テーマに合った短い言葉を書く。（桜舞う、や新緑が、\nなど）\n⑤一定時間経ったら支援者が合図を出し、次の対象者へ紙を回す。\n⑥紙が回ってきた対象者は、書かれている言葉につながる言葉を考えて書き、合図があったら次へ回す。\n⑦あらかじめ決めておいた回数を回し終えたら終了。\n⑧どんな詩が完成したか発表する。",
    youtubeId: "9MFDdpV0x6o",
  },
  {
    category: "学校レク",
    title: "ステレオコール",
    publishedAt: "2020-11-06",
    description: "ステレオコール",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①出題する子どもが前に出る。\n②答えとなる言葉を決める。（みかん、など）\n③出題者に一文字ずつ割り当てる。\n④出題者が自分に割り当てられた文字を一斉に発声する。\n⑤他の子どもたちは解答者になって聞き分けて答える。",
    youtubeId: "26eG4LwjmLo",
  },
  {
    category: "幼児レク",
    title: "吹きゴマ",
    publishedAt: "2021-11-30",
    description: "吹きゴマ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "6cphKY7OCgg",
  },
  {
    category: "幼児レク",
    title: "たんぽぽのびんづめ",
    publishedAt: "2021-11-02",
    description: "たんぽぽのびんづめ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "UIT3HRQR8E0",
  },
  {
    category: "幼児レク",
    title: "ゴロゴロジャンプ",
    publishedAt: "2021-10-04",
    description: "ゴロゴロジャンプ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "_stjQIIbtCw",
  },
  {
    category: "幼児レク",
    title: "よしお兄さんとうたおう！『うみ』",
    publishedAt: "2021-08-30",
    description: "よしお兄さんとうたおう！『うみ』",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Bqzc0cBF0c4",
  },
  {
    category: "幼児レク",
    title: "コロコロストップ",
    publishedAt: "2021-08-30",
    description: "ボールを指定の場所に止まるように転がします",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Mt-KBV6YfIc",
  },
  {
    category: "幼児レク",
    title: "キーボードタッチ",
    publishedAt: "2021-08-30",
    description: "指示された数字をタッチします",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "SqANUJu2hLc",
  },
  {
    category: "幼児レク",
    title: "ひもあそび",
    publishedAt: "2021-08-30",
    description: "ひもであそび",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "GLS3o3imksQ",
  },
  {
    category: "幼児レク",
    title: "くるくる紙コップ",
    publishedAt: "2021-06-07",
    description: "紙コップがくるくる回転して飛びます",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "V_u9oTnCsCg",
  },
  {
    category: "幼児レク",
    title: "だるまさんが転んだ",
    publishedAt: "2021-05-19",
    description: "だるまさんが転んだ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "ZHM8f2AEv6w",
  },
  {
    category: "幼児レク",
    title: "からだでバスケシュート",
    publishedAt: "2020-12-23",
    description: "からだでバスケシュート",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "mUrVog3uBHs",
  },
  {
    category: "幼児レク",
    title: "忍者とび",
    publishedAt: "2020-11-06",
    description: "忍者とび",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "rNTMf33yEeE",
  },
  {
    category: "幼児レク",
    title: "おはなしゆびさん",
    publishedAt: "2020-11-06",
    description: "おはなしゆびさん",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "wY0boe4-zhE",
  },
  {
    category: "幼児レク",
    title: "よしお兄さんとなわとび しょきゅうへん",
    publishedAt: "2020-11-06",
    description: "よしお兄さんとなわとび しょきゅうへん",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "hnw4MAC37hg",
  },
  {
    category: "幼児レク",
    title: "グーチョキーパーでなにつくろう♪どうぶつバージョン",
    publishedAt: "2020-11-06",
    description: "グーチョキーパーでなにつくろう♪どうぶつバージョン",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "9FUOslsd7Ac",
  },
  {
    category: "幼児レク",
    title: "よしお兄さんの「てあそびうたミックス」",
    publishedAt: "2020-11-06",
    description: "よしお兄さんの「てあそびうたミックス」",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "ZmPXJrS7GhM",
  },
  {
    category: "幼児レク",
    title: "よしお兄さんの「あわてんぼうのサンタクロース」",
    publishedAt: "2020-11-06",
    description: "よしお兄さんの「あわてんぼうのサンタクロース」",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "IDhi1msohgI",
  },
  {
    category: "幼児レク",
    title: "BEYOOOOONDSとよしお兄さんとあそぼう",
    publishedAt: "2020-11-06",
    description: "BEYOOOOONDSとよしお兄さんとあそぼう",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "Mcfj_O904BE",
  },
  {
    category: "幼児レク",
    title: "自由なパスあそび",
    publishedAt: "2020-11-06",
    description: "自由なパスあそび",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "7fVaZg6q31E",
  },
  {
    category: "幼児レク",
    title: "コロコロ8の字",
    publishedAt: "2020-11-06",
    description: "コロコロ8の字",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "NUgCHivw3j0",
  },
  {
    category: "幼児レク",
    title: "リングキャッチ",
    publishedAt: "2020-11-06",
    description: "リングキャッチ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "UKLHSkY2Cyw",
  },
  {
    category: "幼児レク",
    title: "リングフープ",
    publishedAt: "2020-11-06",
    description: "リングフープ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "OmGLoPGdXYM",
  },
  {
    category: "幼児レク",
    title: "マンカラ",
    publishedAt: "2020-11-06",
    description: "マンカラ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "w9joCK5PCpk",
  },
  {
    category: "幼児レク",
    title: "ニチレクボール・チャレンジ",
    publishedAt: "2020-11-06",
    description: "ニチレクボール・チャレンジ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "0aiaVw9ioAo",
  },
  {
    category: "幼児レク",
    title: "そーれで拍手",
    publishedAt: "2020-11-06",
    description: "そーれで拍手",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①教師の「そーれ」の合図で子どもたちは拍手を1回行う。\n②続いての「そーれ」では2回、その次は3回、と連続して行いそのたびに数を増やしていく。\n③拍手が揃う心地よさを感じながら行い、教師が「そこまで」と言ったところの回数の人数でグループを作り座る。\n④数を変えて何度か行い、グループになるたびに自己紹介などをすると交流ができる。",
    youtubeId: "6VtvhMLvmAo",
  },
  {
    category: "幼児レク",
    title: "だるまさん",
    publishedAt: "2020-11-06",
    description: "だるまさん",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①教師が「ダルマさん〇〇してください」と言った時だけ、子どもは言われた動作を行う。\n（「ダルマさん、右手を上げて下さい」と言われたら、子どもは右手を上げる）\n②“ダルマさん”という言葉がつかない時は、従ってはいけない。\n③教師は“ダルマさん”という言葉を入れたり、入れなかったりしてフェイントをかける。\nまた、多くの子の間違いを誘い、緊張を開放していく展開もある。",
    youtubeId: "c6YP1_Vu55Q",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "チャレンジ・ザ・ゲーム～学校教育編～",
    publishedAt: "2024-03-27",
    description:
      "チャレンジ・ザ・ゲームとは平成元年に日本レクリエーション協会が考案し、全国各地で幅広い年齢層に親しまれているスポーツ・レクリエーションです。2023年現在の時点で12種類あり、体力や年齢に応じて自分に合った種目を選択できるのも魅力の一つです。体力や技術、勝敗を競うのではなく、グループで交流を楽しみながらできるため、運動経験の少ない方、苦手な方でも気軽に取り組むことができます。近年は学校教育現場での活用が広がっていることでも注目されています。\n\r\nこの動画では、チャレンジ・ザ・ゲームの種目の1つであるスピード・ラダーゲッターを取り入れて、年間を通して運動や外遊びをする機会を増やす習慣をつくり、体力向上はもちろん、元気いっぱいの心を育てることを目的とした神奈川県横浜市の小学校での取り組みを紹介します。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "学習指導要領では、子どもの体力向上や心身の健康増進のために、授業での取り組みに加え、授業以外の時間や学校外での日常生活までを視野に入れて、体育・健康に関する指導を行うことが大切であるとしています。具体的な場面としては、授業を行う前に行われる体育的活動である業前体育や、休み時間などに行われる業間体育などがあります。\n簡単なルールで、学年差に関係なく取り組めることから、これまでも業前・業間体育で多く活用されてきました。体育の授業で活用するとともに、業前・業間体育の場面と連動して実施することで、クラスや学年を超えた交流や体力づくりの活動がさらに広がっています。\nまた、チャレンジ・ザ・ゲームは、グループ内で声を掛け合い、息が合わなければ、いくら運動能力の高い人が集まったとしても、決して記録は伸びません。そこで大切なのが「チームワーク」です。グループ内で交流を深め、他のメンバーを思いやり、心を一つにすることです。記録に挑戦していくうちに、チームワークが高まっていくのもチャレンジ・ザ・ゲームの効果といえます。",
    youtubeId: "LmrM8sfluMc",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "チャレンジ・ザ・ゲーム",
    publishedAt: "2024-03-27",
    description:
      "チャレンジ・ザ・ゲームは、グループで交流しながら記録に挑戦し、遊び感覚で体を動かす楽しさを味わえる”新感覚”のスポーツ・レクリエーションです。ボールを使ったり、ロープやスティックを使ったりなど、ユニークなゲームがたくさんあります。また、一年中、いつでも、どこでも、記録を申請することで参加できるユニークな大会「全国いつでもチャレンジ・ザ・ゲーム大会」を開催しています。学校や職場、地域など、さまざまな場面で、たくさんの方々に楽しまれています。",
    numOfPlayers: "2人から",
    howLong: "--",
    detail:
      "チャレンジ・ザ・ゲームは、平成元年に日本レクリエーション協会が考案し、以降、全国各地で幅広い年齢層に親しまれているスポーツ・レクリエーションです。技術や体力、勝敗を競うのではなく、グループでの交流を楽しみながら記録に挑戦します。\n遊び感覚で身体を動かすことができるため、運動が苦手な人や体を動かすことが嫌いな人でも、楽しみながら取り組むことができます。ボールや縄、棒といった用具を使うユニークな種目がたくさんあるため、体力や年齢に応じて自分に合った種目を選択することができるのも、魅力の一つです。\nまた、挑戦した記録を申請することで、月間、年間単位で全国ランキングを競うという「全国いつでもチャレンジ・ザ・ゲーム大会」に参加することができます。小中学校や、職場、地域などのさまざまな場面で、たくさんの方々がチャレンジ・ザ・ゲームを楽しんでいます。",
    youtubeId: "9Ozb628sTiw",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "ニチレクボール・チャレンジ",
    publishedAt: "2024-03-27",
    description:
      "３メートル離れた場所に置いた目標球（ビュット）に、６個のニチレクボールを全部当てた後、全員でビュットを含む全てのボールの外側を同じ方向に周回して戻るまでのタイムを競います。",
    numOfPlayers: "3人から",
    howLong: "--",
    detail:
      "【人数】\n１チーム３人以上。\n【隊形】\n先頭だけニチレクボールを１個持って、縦一列にスタートラインに待機。\n【用具】\nＣＧ推進本部公認の専用用具（ニチレクボール６個、ビュット１個）\n【カウント】\nスタートの合図でニチレクボールを全てビュットに当てた後、全員が全てのボール（ビュット含む）の外側を同じ方向に周回して戻るまでのタイムを計時。",
    youtubeId: "bNy_nKnaBbQ",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "チームふらば～るボール",
    publishedAt: "2024-03-27",
    description:
      "４人が４メートル離れて四角形を作り、ふらば～るをワンバウンドパスして、２分間で全員がキャッチに成功した回数がカウントされ合計数が記録となります。",
    numOfPlayers: "4人",
    howLong: "2分",
    detail:
      "【人数】\n１チーム４人。\n【隊形】\n仲間との間隔を４mあけ、全員がふらば～るを１個ずつ持ち、スロー＆キャッチしやすい向きで待機する。\n【用具】\nＣＧ推進本部公認の専用用具（ふらば～る大３個、小１個）\n【カウント】\n全員がふらば～るのキャッチを成功するごとにカウント。成功した回数が記録となる。",
    youtubeId: "Bua4AYORgsY",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "スピード・ラダーゲッター",
    publishedAt: "2024-03-27",
    description:
      "ボールを投げて、全てのラダーにどれだけ早くかけられるかを楽しむゲーム。",
    numOfPlayers: "3人から6人まで",
    howLong: "2分",
    detail:
      "【人数】\n１チーム３～６人\n【隊形】\n先頭だけ専用ボールを持って、縦一列にスタートラインに待機する。\n【用具】\nラダーゲッター（レクリエーション・カタログ）\n【カウント】\nスタートの合図から全てのラダーに１個ずつボールがかかった後、全員でラダーを周回して戻るまでのタイムを計時。",
    youtubeId: "_ZWtu3m-FXE",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "ペア・リング・キャッチ",
    publishedAt: "2024-03-27",
    description:
      "向い合った2人が3本以上のリングをまとめて投げ合い、トータルでいくつのリングをキャッチできるかを競う、少人数で楽しめる種目です。2人の距離は、お互いの両手を大きく広げた距離の長さなので、子ども同士であれば距離は短く、大人であれば長くなるので、異年齢の対抗戦も楽しめます。",
    numOfPlayers: "2人から",
    howLong: "2分",
    detail:
      "【人数】\n1チーム2人\n【隊形】\n2人はニュートラルゾーンを挟んで向かい合います。どちらか一方がリングを3本以上持ちます。\n【用具】\nチャレンジ・ザ・ゲーム推進本部公認ゴム製リング3本以上（直径16.5cm、太さ3cmの円形で赤または黄色）。\nペア・リング・キャッチセット（リングテニス6個）\nリングテニス用リング（赤）（直径約17cm・重量180～190g）\nリングテニス用リング（黄）（直径約17cm・重量180～190g）\n【カウント】\nキャッチしたリングの本数をカウントします。成功した本数を加算したものを記録とします。",
    youtubeId: "Bn4-jvfR1nE",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "キャッチング・ザ・スティック",
    publishedAt: "2024-03-27",
    description:
      "10人が横一列に並び、向かって右から8人がスティック(2本）を持ち、左側の 2人が待機。はじめ「セーノ、トン、トン、パッ」の掛け声に合わせ、スティックを床に2回突き、「パッ」で右隣の人の2本のスティックを移動してキャッチ。全員が 成功したら1カウントで、 リズムに合わせて何回続けられるかを楽しみます。",
    numOfPlayers: "10人から12人まで",
    howLong: "--",
    detail:
      "【人数】\n１チーム10人。（補欠は2名まで可）\n【隊形】\nメンバーの内8人がひとり2本のスティックを両手で持ち、横一列に並びます。スティックを持っていない2人は列の左端に並びます。\n【用具】\nチャレンジ・ザ・ゲーム推進本部公認スティック16本\n【カウント】\nキャッチに成功して移動するたびにカウントします。連続して成功した回数が記録となります。",
    youtubeId: "ZkIzEyPWYxY",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "ロープ・ジャンプ・X",
    publishedAt: "2024-03-27",
    description:
      "長さ10ｍのロープを使ったなわとびで、３人以上であれば何人でも楽しめます。小さいグループでも、学校のクラス単位でも競い合えるのが魅力です。運動量もあり、子どもから壮年の方まで、幅広い人たちに人気があります。",
    numOfPlayers: "3人から",
    howLong: "--",
    detail:
      "【人数】\n１チーム３人以上～\n【隊形】\nロープの回し役２人がロープを持ち、跳び役は並びます。\n【用具】\nCG推進本部公認ロープ\n【カウント】\n３回チャレンジ。記録は跳んだ人数×跳んだ回数をポイントして記録。",
    youtubeId: "1YOtnAaxm_w",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "ネット・パス・ラリー",
    publishedAt: "2024-03-27",
    description:
      "ネットにボールを載せて持ち、ペア2組で向かい合い、ネットの上のボールを交換して楽しみます。目を合わせ、呼吸をそろえ、声を掛け合うのが成功のポイント。小グループ内でのふれ合いや交流づくりを演出するのにも適しています。",
    numOfPlayers: "4人から",
    howLong: "2分",
    detail:
      "【人数】\n１チーム4人（2人×2組）\n【隊形】\n各ペアはニュートラルゾーンを示す3.6ｍの間隔で引かれたラインを挟んで立ち、両ペアがネットにボールを載せる。\n【用具】\nCG推進本部公認チャレンジ・ザ・ゲーム推進本部公認ネット。または50cm×100\ncmの大きさのネットで網目の大きさが45mm以下。ネットの素材はポリエチレンまたはナイロン製のもの（2枚）。ドッジボール3号球2個。\n【カウント】\nパス＆キャッチが成功するたびにカウントします。記録は成功した回数を加算します。",
    youtubeId: "r5m049-EEUs",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "手のひら健康バレー2分間勝負",
    publishedAt: "2024-03-27",
    description:
      "専用のボール（30ｇ）とネットを用いて、ネット越しにボールの連続パスを２分間で何回できるかを競います。",
    numOfPlayers: "6人",
    howLong: "2分",
    detail:
      "【人数】\n１チーム６人\n【隊形】\n専用のネットをはさんで３人ずつ分かれ向かい合って椅子に座る。\n椅子はネットから50cm離して向かい合わせに設置。\nネットの高さ110cm\n【用具】\nＣＧ推進本部公認の専用用具（手のひら健康バレーと専用ネット）／椅子・・６脚\n【カウント】\n競技時間内にアウトにならずネットを超えた回数の合計がチームの得点となる。",
    youtubeId: "NUKKNVVCOvc",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "ゴム・ダンス・“ステっぴょん”",
    publishedAt: "2024-03-27",
    description:
      "これまで跳び役が2人のところを1人すつ跳ぶルールに改訂。5人以上（リズムキー ー 2人／跳び役3人以上）で、何人が規定のステップを行うことができたかを競う。",
    numOfPlayers: "5人から",
    howLong: "2分",
    detail:
      "【人数】\n1チーム5人以上（リズムキーパー２人／跳び役３人以上）\n【隊形】\nリズムキーパーの２人は、両足首にゴムをかけて向かい合う。跳び役が１人入っていき、規定のステップを１サイクルステップし、ゴムから抜けたところで次の人が入る。\n【用具】\n幅５mm以上１５mm以下で、長さ３ｍ以上のゴムを結んで1本の輪状にしたもの\n【カウント】\nスタートの合図から先頭の１人の片足が既定のステップを成功した人数をカウント。成功した回数を加算して記録。",
    youtubeId: "rqEsvVL68y0",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "チームテンカボール",
    publishedAt: "2024-03-27",
    description:
      "キャッチの仕方でポイントが変わるボールスロー＆キャッチのゲーム。制限時間内にどれだけポイントを獲得できるかを楽しみます。取りやすいようにスローして、高得点を稼げるキャッチを続けてみよう。",
    numOfPlayers: "4人から",
    howLong: "2分",
    detail:
      "【人数】\n１チーム４人。\n【隊形】\n仲間との間隔を４ｍ空け、１人がボールを持ち、残りのメンバーはキャッチ＆スローしやすい向きで待機する。\n【用具】\nＣＧ推進本部公認の専用用具（テンカボール）またはソフトバレーボール\n【カウント】\nボールをキャッチするごとにキャッチの方法によるポイントを加算する。",
    youtubeId: "JQs5uZlgzYk",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "音楽レクリエーション~あそびうた 指導実践編~",
    publishedAt: "2023-03-28",
    description:
      "音楽レクリエーションは、公益財団法人日本レクリエーション協会が推進する、音楽を用いたレクリエーション活動の総称です。音楽レクリエーションといっても、「わらべうた」や「あそびうた」のように、歌やリズムに合わせて遊んだりゲームをする活動、「うた体操」のように、親しみのある歌に合わせて身体（からだ）を動かす活動、季節を感じる歌や、かつて親しんだ流行歌をみんなと楽しむ活動、懐かしいうたをきっかけに回想や交流を楽しむ活動、音に耳を傾け、即興的な創作を楽しむ活動など、幅広く展開することができます。\n\r\nこの動画では、魅力満載の音楽レクリエーションから3つの「あそびうた」の進め方をご紹介します。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "あそびうたの中から「リズム手合わせ」「リズム膝たたき」「二拍子三拍子」の実際の進め方を解説します。",
    youtubeId: "WYr1pJlZs3w",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "音楽レクリエーション あそびうた",
    publishedAt: "2023-03-28",
    description:
      "音楽レクリエーションは、公益財団法人日本レクリエーション協会が推進する、音楽を用いたレクリエーション活動の総称です。音楽レクリエーションといっても、「わらべうた」や「あそびうた」のように、歌やリズムに合わせて遊んだりゲームをする活動、「うた体操」のように、親しみのある歌に合わせて身体（からだ）を動かす活動、季節を感じる歌や、かつて親しんだ流行歌をみんなと楽しむ活動、懐かしいうたをきっかけに回想や交流を楽しむ活動、音に耳を傾け、即興的な創作を楽しむ活動など、幅広く展開することができます。\n\r\nこの動画では、魅力満載の音楽レクリエーションから「あそびうた」をご紹介します。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "「あそびうた」は、シンギング・ゲームやレク・ソングと言われ、リズムに合わせてゲームをしたり、二つの歌を一緒に歌ってハーモニーを奏でたり、歌をつかっていろいろな遊び、楽しみ方ができるのが特徴です。\nまた、みんなで楽しむことで、一体感が生まれるため、仲間づくり、集団づくりにも役立ちます。ほかにも、考えたり、集中したり、脳を活性化させるあそびが豊富にあり、認知症予防として、地域の高齢者サロンや高齢者福祉施設でも多く実施されています。そんな魅力いっぱいの「あそびうた」について、いろいろなバリエーションを紹介します。\n・リズム手合わせ\n・リズム膝たたき\n・二拍子三拍子\n・輪唱・おいかけ歌\n・パートナーソング\n・ベース音にメロディを乗せて歌う",
    youtubeId: "1Tuho1Ef7mA",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "音楽レクリエーション うた体操",
    publishedAt: "2023-03-28",
    description:
      "音楽レクリエーションは、公益財団法人日本レクリエーション協会が推進する、音楽を用いたレクリエーション活動の総称です。音楽レクリエーションといっても、「わらべうた」や「あそびうた」のように、歌やリズムに合わせて遊んだりゲームをする活動、「うた体操」のように、親しみのある歌に合わせて身体（からだ）を動かす活動、季節を感じる歌や、かつて親しんだ流行歌をみんなと楽しむ活動、懐かしいうたをきっかけに回想や交流を楽しむ活動、音に耳を傾け、即興的な創作を楽しむ活動など、幅広く展開することができます。\n\r\nこの動画では、魅力満載の音楽レクリエーションから「うた体操」をご紹介します。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "「うた体操」は文字通り、うたに合わせて行う体操のこと。「ゆっくりストレッチタイプ」「健康づくりタイプ」「体力アップタイプ」「座って楽しむタイプ」など、目的に合わせてさまざまなバリエーションの「うた体操」を作ることができます。ここでは介護予防教室や高齢者福祉施設などで行う「うた体操」を作る際のポイントをご紹介します。",
    youtubeId: "BmhVgzdU-e8",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "フライングディスク",
    publishedAt: "2023-03-22",
    description:
      "小・中学校の保健体育の授業において、フライングディスクを使用した競技を採用されている先生方も多いのではないでしょうか。ただ、授業の中で展開していくにしても、どのように指導していくべきかという点で、不安に思われる先生もいらっしゃるかもしれません。\n\r\nこの動画では先生方の指針になるような、指導方法およびプランについて紹介しています。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "フライングディスクの数ある種目の中で、学校教育現場で最も取り入れられているのがアルティメットです。アルティメットという競技は、パスのみでフライングディスクをつなぎ、コート両端に設定された相手陣地のエンドゾーン内でディスクをキャッチすれば得点できるというゲームです。\nアルティメットを通じて運動技能の向上、チーム競技としての助け合いや協力関係の構築、試合中はセルフジャッジをするなど、フェアプレー精神の醸成などを培うことができます。ぜひ先生方の授業にお役立てください。",
    youtubeId: "TPqwD_dzlCA",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "ウォークラリー大会を成功させよう",
    publishedAt: "2023-03-22",
    description:
      "ウォークラリーは、健康づくり、地域文化の見どころの再発見、家族や仲間同士のコミュニケーション促進など、多くの人に楽しんでもらいながら目的に合わせた企画ができる人気のスポーツ・レクリエーションプログラムです。\n\r\nこの動画では、ウォークラリーイベントを円滑に進め、参加者にもしっかり楽しんでもらうための運営方法をいくつかのポイントに分けて紹介します。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "ウォークラリーは老若男女を問わず、誰でも参加できることから、集客イベントとしてはお薦めのレクリエーション・プログラムです。ウォークラリー大会を開催するにあたり、以下のポイントを参考にしながら、ぜひ、みなさんの学校や地域などで、独自性のウォークラリーを開催してみてください。\n①ウォークラリー大会の全体像を描く\n②コースづくり\n③コマ図のつくり方\n④チェックポイントの課題\n⑤順位の決め方とゴール後のイベントについて",
    youtubeId: "-8qyClgovaI",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "インディアカ",
    publishedAt: "2023-03-22",
    description:
      "赤い大きな羽のついたボールをバレーボールのように味方同士でつないで得点をうばいあう健康スポーツ「インディアカ 」。\n\r\n「コミュニケーションを育む」「身体能力向上が期待できる」「自己肯定感を高める」ことなどから、小中学校の保健体育はもちろん、運動部地域移行における多種目型クラブにも導入しやすいスポーツとして期待されています。\n\r\nこの動画では、小中学校などの教育現場でインディアカを導入する際に無理なく取り組めるよう、インディアカの基本指導について紹介しています。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "インディアカの指導の進め方を紹介します。\n①投げる・捕る\n②ボールを打って返す\n③サーブ練習\n④ボールをつなぐ\n⑤簡単なゲームへ",
    youtubeId: "iTczhBFBpWc",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "キャンプ初心者のための基礎講座",
    publishedAt: "2023-03-20",
    description:
      "近年、人気のアクティビティとして注目されているキャンプ。ブームに伴い、キャンプを楽しむ人は急増しましたが、ゴミやマナー問題、環境破壊など、一部の人のルール違反などが社会問題となり、キャンプそのものにマイナスイメージが広がり、このままでは地域や自治体によるキャンプへの規制が厳しくなる恐れがあります。そこで誰もがキャンプを安全に、安心して楽しめるようにと、日本キャンプ協会が「グッドキャンパー宣言」を定めました。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "グッドキャンパー宣言では、キャンプをするうえで大切なことをまとめた「グッドキャンパーの心得8か条」を策定しています。ビギナー、ベテランを問わず、この価値観に賛同したキャンパー自身がグッドキャンパーであることを宣言することで、キャンプの健全な楽しみ方を社会に広めていくことをねらいとしています。\nこの動画では、グッドキャンパー宣言をはじめ、キャンプ初心者の方にぜひとも知っていただきたい基礎知識を紹介しています。",
    youtubeId: "OoD6HG5wPY8",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "防災ウォーク 備（そなえ）",
    publishedAt: "2023-03-20",
    description:
      "日本ウオーキング協会が考案したウォーキングを通じて防災について学ぶことができる市民参加型のウォーキングイベント「防災ウォーク 備（そなえ）」。ここでは福島で行われたプログラムを紹介しています。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "福島で行われた「防災ウォーク\n備」は、防災に関する知識を学ぶ座学、器具を使ったワークショップ、実際にまちへ出て、災害時を想定した歩き方などを学ぶウォーキングの3部で構成で行われました。ぜひともみなさんのまちでも、ウォーキングという手段を使って「防災ウォーク\n備」を開催してみてはいかがでしょうか。",
    youtubeId: "V4hTZXe_-tY",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "集団用とびなわ",
    publishedAt: "2023-03-20",
    description:
      "「集団用とびなわ」とは、日本レクリエーション協会が公認するレクリエーション用具のひとつです。グリップ部分は68cmと長く、回し手の負担を軽減。ロープの長さは10ｍ、太さ1cmで、ロープの中には芯が入っているので、安定して回しやすいのが特徴のとびなわです。集団用とびなわを使った遊びである大縄跳びには、持久力アップ、筋力アップ、リズム感、協調性、集中力、チャレンジ精神、団結力など、さまざまな力が身につくと言われており、教育現場、職場、地域など、さまざまな現場で活用されています。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "集団用とびなわに慣れてもらうためのリードアッププログラムから、日本レクリエーション協会が主催する「全国いつでもチャレンジ・ザ・ゲーム大会」の大会種目となっている「ロープ・ジャンプ・X」「ロープ・ジャンピング・10」の遊び方を紹介しています。",
    youtubeId: "tTgAHEYRYrI",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "ニチレク・スティック",
    publishedAt: "2023-03-15",
    description:
      "ニチレク・スティックとは、日本レクリエーション協会が考案した用具のひとつで、スティックを使って多彩なレクリエーション活動が行えます。スティックの長さは約1m。セットにはそのスティックが16本付属しています。そのため、少ない人数で遊ぶことはもちろん、クラス全体で行う学級レクにも使えるなど程よい運動、生徒同士のコミュニケーションの促進など幅広い用途に役立てることができます。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "1人でも遊べる遊びから、徐々に人数を増やして遊べる遊びを紹介します。最終的には日本レクリエーション協会が主催する「全国いつでもチャレンジ・ザ・ゲーム大会」の大会種目のひとつとなっている「キャッチング・ザ・スティック」への記録申請に挑戦してみましょう！\n①カウントキャッチ\n②クラップキャッチ\n③スピードキャッチ\n④ペアスティックチャレンジ\n⑤スティックボールリレー\n⑥ドンパーリレー\n⑦ドンパーリレーⅡ\n⑧キャッチング・ザ・スティック",
    youtubeId: "rMMlOoySrF8",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "健康スポーツ",
    publishedAt: "2022-03-23",
    description:
      "スポーツってなんだろう？　野球、サッカー、陸上、テニス、水泳…。スポーツと聞いて思い浮かぶのは勝ち負けを競う「競技種目」ではないでしょうか。そもそもスポーツという言葉はラテン語の「DEPORTARE」に由来し、運び去る・運搬するという意味から精神的な次元の移動や返還へと転じ、「義務からの気分転換・元気の回復」という意味合いで使われるようになったと言われています。つまり、人生を楽しみ、元気に生きるための「気晴らし」「楽しみ」「休養」こそがスポーツの本質なのです。そんな広い意味を持つスポーツの中に、近年、競技スポーツとは一線を画し、注目を集めているジャンルがあります。それが「健康スポーツ」です。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "スポーツをはじめたい。しかし、どんなスポーツが自分に合っているのか分からない。そんな方はいませんか？\nこの動画では、運動が苦手な方はもちろん、初心者でも気軽に楽しめる健康スポーツを紹介しています。\n健康スポーツは、「障がいがあっても楽しめる」「勝ち負けにこだわらない」「初心者でも運動が苦手でも長く楽しく続けられる」「みんなが1つになって体を動かす、笑う、交流する」を特長とするものです。この動画を見て、みなさんも健康スポーツをはじめてみませんか！",
    youtubeId: "il2hMsJKwf8",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "健康スポレクひろば",
    publishedAt: "2022-03-23",
    description:
      "いつまでも健康で若々しく、アクティブな毎日を送りたい。そんなシニア世代のみなさんの想いに応え、健康づくりをサポートする、とっておきの場。それが「健康スポレクひろば」です。運動やスポーツ・レクリエーションに親しんでいない高齢者にスポーツ・レクリエーション活動がもたらす健康への効果を伝え、継続的にスポーツ・レクリエーションを楽しんでもらうことを目的に、日本レクリエーション協会ならびに、都道府県レクリエーション協会、市区町村レクリエーション協会などが中心となって展開する活動です。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "日本の高齢化率はすでに25%を超えており、今後、ますます高齢者は増大し、2050年には38.8％になると予測されております。こうした中、介護や医療にかかる経費を抑制し、豊かで元気な成熟社会の実現のためには、高齢世代の健康寿命延伸が不可欠となっています。一方、スポーツ・レクリエーションがもたらす心身の健康と元気を維持する効果の高さは、ますます明瞭となり、スポーツ・レクリエーションの必要性は高まっています。\nさらに国は、成人のスポーツ実施率を65%まで高める目標を掲げており、そのためにも運動やスポーツ・レクリエーションに親しんでいない成人、特に高齢世代の方々を、いかにスポーツ・レクリエーションを継続的に実施頂くように促すかが、大きな課題となっています。\nそこで、これまで運動に親しんでいない高齢世代（特に比較的元気な前期高齢者）に、スポーツ・レクリエーションを継続的に実施してもらうことを目的に日本レクリエーション協会が中心となって全国で展開している事業が「健康スポレクひろば」です。\nスポーツ庁では、平成30年9月6日に「スポーツ実施率向上のための行動計画」～「スポーツ・イン・ライフ」を目指して～を策定しました。その中に、高齢者向けの取組として、「相対的にスポーツ実施率は高いが、健康・体力保持等が必要であり、体力低下にも配慮したスポーツを継続できる環境づくりが求められる」「スポーツにより生活習慣病の改善や介護予防等が期待される」との記述がされ、身近なコミュニティにおけるスポーツ機会の提供やスポーツを習慣化するための施策を進めております。\n「健康スポレクひろば」は、健康寿命延伸を目的とした事業で、このような国の方向性に添って実施しています。",
    youtubeId: "5Ml7Ge7gO2w",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "ラダーゲッター",
    publishedAt: "2022-03-18",
    description:
      "ラダーゲッターは、ヒモでつながっている２個のボールをラダー（ハシゴ）に向かって投げ、ボールがラダーに引っ掛かる（ハングする）と得点となる三世代交流も可能なスポーツ・レクリエーションです。\n\r\nルールは簡単で、投げたボールがラダーにハングすると、表示されている数字がポイントになります。\n\r\n基本となる投げ方は、２個あるボールのうち片方のボールを手に持ち、もう片方のボールを下に垂らしてゆっくり前後にスイングし、ボールが後方回転しながら山なりに飛んでいくようにアンダーハンドで投げます。\n\r\n３本あるラダーには、下から１、２、３とポイントが表示されていて、それぞれのラダーにハングしたボールの数×表示されたポイントの合計ポイントを競います。\n\r\nただし、投げたボールが床にバウンドして３本あるいずれかのラダーにハングした場合は、表示されている数字に関係なくハングしたボールの数×５ポイントとなります。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "【プレーの基本】\n・プレーヤーは同じ色のボールを三つ使用します。\n・プレーヤーはファ−ルラインの後ろから、\n7.5ｍ\n離れたラダーに向かってボールを投げます。\n・ボールを投げる時は、必ずボールを持ちアンダースローとします。\n・ボールの位置をずらすことは出来ますが、紐を結ぶなどの加工は出来ません。\n・ボールがうまくラダーにハングすればポイントを得られます。ボールが床に落ちてしまったり、他のプレーヤーによってはじかれてしまった場合はポイントとなりません。\n【ボールの投げ方（基本）】\n・投げる時は片方のボールを持ち、もう片方のボールを垂らした状態で、前後にゆっくりスイングします。\n・狙いのラダーに、スイングしているボールの先端が向いていることを確認します。\n・狙いのラダーに、スイングしてい振り子の反動を上手く使いラダーに向かって投げます。そうするとボールは後方回転しながら山なりに飛んでいきます。\n【得点】\n・一番上のラダーにボールがハングする：３点\n・真ん中のラダーにボールがハングする：２点\n・一番下のラダーにボールがハングする：１点\n・ラダー手前の床や地面にバウンドしていずれかのラダーにボールがハングする：５点\n※バウンドした場合の得点は、どのラダーにハングしても５点です。（床や地面の材質などによってバウンドが異なるため）\n※事前にヒモの色で投げる順番を決めましょう。投げたボールの順番が分かるように、３色あるヒモの投げる順番を決めておくと判定しやすくなります。\n【勝敗】\n・１試合５セットマッチとし、３セット先取したプレーヤーが勝者となります。\n・１セットは、21点先取したプレーヤーが勝者となります。\n・ただし、ぴったり21点で終わる必要があります。\n・先攻プレーヤーと後攻プレーヤーが同じラウンドで同時に２１点を獲得した場合は、次のラウンド終了時に得点の高かったプレーヤーがそのセットの勝者となります。\n＊セットは勝敗が決まった状態、ラウンドは全てのボールが投げ終わった状態（放棄したボールは除く）。",
    youtubeId: "6gSglpf7KAs",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "おうちで60秒チャレンジ",
    publishedAt: "2022-03-18",
    description:
      "「おうちで60秒チャレンジ」は、自宅で、家族でできるレクリエーション活動（からだを動かすあそび）です。外出の自粛や休校による自宅待機が続く中、運動不足やストレスなどの課題に対応する取り組みとしてスタートしました。\n\r\nコンセプトは、「身近な物を使う！」「適度な運動量がある！」「あそび方はシンプル！」「夢中になれる！」「見ていて楽しい！」こと。\n\r\n新聞紙スティックを倒さないようにすばやくキャッチしたり、新聞紙リングでペットボトルをゲットしたり、目隠しをして60秒ピッタリを目指したり。家の中で、家族で協力しながらチャレンジできるものばかりです。\n\r\n是非、みなさんも一緒にチャレンジしましょう！",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "「おうちで60秒チャレンジ」の様子を撮影して、動画をTwitterに投稿してみませんか。\n日本レクリエーション協会公式アカウントが、みなさんの投稿をリツイートさせていただきます。\nリツイートさせていただいた最新情報は、随時ホームページ上で更新されますので、楽しんでいる様子や好記録の様子などが全国の方々と共有できます。ハッシュタグ「#おうちで60」と「#スポーツインライフ」をつけて、みなさんの投稿お待ちしています！",
    youtubeId: "FIVb45vaipg",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "チャレンジ・ザ・ゲーム",
    publishedAt: "2022-03-18",
    description:
      "チャレンジ・ザ・ゲームは、平成元年に日本レクリエーション協会が考案し、以降、全国各地で幅広い年齢層に親しまれているスポーツ・レクリエーションです。技術や体力、勝敗を競うのではなく、グループでの交流を楽しみながら記録に挑戦することができます。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "チャレンジ・ザ・ゲームは、技術や体力、勝敗を競うのではなく、グループでの交流を楽しみながら記録に挑戦します。\n遊び感覚で身体を動かすことができるため、運動が苦手な人や体を動かすことが嫌いな人でも、楽しみながら取り組むことができます。ボールや縄、棒といった用具を使うユニークな種目がたくさんあるため、体力や年齢に応じて自分に合った種目を選択することができるのも、魅力の一つです。\nまた、挑戦した記録を申請することで、月間、年間単位で全国ランキングを競うという「全国いつでもチャレンジ・ザ・ゲーム大会」に参加することができます。小中学校や、職場、地域などのさまざまな場面で、たくさんの方々がチャレンジ・ザ・ゲームを楽しんでいます。",
    youtubeId: "MXPt0_w1SKU",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "フライングディスク",
    publishedAt: "2022-03-02",
    description:
      "フライングディスクの起源は、1940年代に、アメリカ合衆国コネチカット州にあるエール大学の学生が、キャンパス近くの「フリスビー・パイ」というパイ屋のパイ皿を投げて遊んだことが起源とされています。そして、その金属製パイ皿を投げて遊ぶ姿を見たウォルター・フレデリック・モリソンが、1948年にプラスティック製の安全なディスクを作ったのが始まりです。その後、製造・販売の権利をモリソンから取得したワーム・オー(WHAM-O)社が1959年に”Frisbee”の名称を登録商標として売り出したことから世界中に広まりました。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "初期の頃は玩具として使用されましたが、優れた飛行特性を活かした11種目が生み出され、プラスティック製ディスクと11種目を総称する一般名称「フライングディスク」が1984年に制定されました。材質や形状に改良が重ねられた現在のフライングディスクの飛行性能は、最長飛距離「338m」、最高時速「時速140km」、最長滞空時間「16.72秒」とギネスブックに認定されるほど優れたものとなっています。そして、世界フライングディスク連盟(WFDF)は、2015年8月2日にマレーシア・クアラルンプールで開催された第128次国際オリンピック委員会(IOC)総会において、2年間の準承認期間を経て正式に承認団体として認められました。フライングディスクは、2020年東京オリンピック追加競技の最終候補に残ることはできませんでしたが、2028年オリンピック競技になることを目指し、更なる普及に努めています。",
    youtubeId: "_e2I51mmaNE",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "ビリヤード",
    publishedAt: "2022-03-02",
    description:
      "ビリヤードは、青少年から90歳までのスポーツといわれ、世界各国で幅広い年齢層の方々が手軽に楽しまれています。使用するテーブルの形状によって、大きくキャロム競技とポケット競技に分けられ、使用する道具等が若干異なります。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "今やビリヤード人口は1億人を越え、世界でもトップクラスのスポーツとして位置付けられるようになりました。世界および大陸選手権のほとんどで、19歳以下のジュニア選手権が開\n催されています。\nまた、ビリヤードは、急速に進む日本の高齢化社会において、より安全で有効な運動として注目を集めいています。高齢者の体力・健康作りのために、全国各自治体・公共団体の施設へのビリヤードテーブルの無償貸与や指導者が派遣されるなど、全国市町村への普及活動も盛んになっています。",
    youtubeId: "5u1YPjn4xm8",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "タッチラグビー",
    publishedAt: "2022-03-02",
    description:
      "タッチラグビー (Touch Rugby) は、ラグビーからタックル、スクラムなどのコンタクトプレーと、キックをのぞいたパスゲームで、より親しみやすい簡易型フットボールです。\n\r\nラグビーで用いられるタックルを安全な「タッチ」に置き換えたスポーツ、それが「タッチラグビー」です。子どもからシニアまで男女問わず楽しむことができ、「誰でも一緒にプレーできる親しみやすさ」が大きな魅力です。\n\r\nラグビー経験者だけではなく、未経験者にも親しみやすく、子供から大人、年配、女性まで楽しめるスポーツです。\n\r\n1960年代に、オーストラリアでラグビーリーグのウォーミングアップとして始められ、徐々に拡がり、ニュージーランド、欧米など多くの国で親しまれるようになりました。競技人口も50万人以上と、人気なスポーツになってきています。\n\r\n日本においても、1989年に日本タッチ協会が設立され、全国各地に10万人にも達しています。\n\r\n公式大会も「JAPANカップ」、「関西大会」、「関東大会」、「学生選手権」など各地で多数開催され、関西でも多くの大会が開催されています。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "タッチラグビーの魅力は、何と言っても老若男女みんなが一緒にプレーすることができる生涯スポーツであること。親子3世代でファミリースポーツとして楽しむこともできます。\n特に子どもにとっては、チームワークから生まれる協調性はもちろんのこと、スポーツマンシップを養うのに最適なスポーツともいえます。というのも、本当にタッチしたのかどうかについては自分にしかわからない局面もあり、誠実さが問われるスポーツだからです。また、タッチという最低限の接触プレーを通じてボディーコントロールが身に付き、前後左右への動きやボールを投げる・捕るといったマルチな運動能力が向上します。\nさらに、4年に一度ワールドカップも開催されているタッチラグビーは、世界約50か国で親しまれ、国際交流を実現するコミュニティースポーツとしての期待が今後ますます高まっていくことでしょう。\n競技スポーツのタッチラグビーの見所としては、スピーディーなゲーム展開と華麗なフットワークやパスワークに注目。それぞれが自分の役割を考えた組織プレーは圧巻です。",
    youtubeId: "8PHvKdtl3zk",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "ダーツ",
    publishedAt: "2022-03-02",
    description:
      "近年わが国は余暇時間の増大と共に急激にスポーツ、レジャー志向が高まってきました。 その中で21世紀のスポーツとして注目されているのが「ダーツ競技」です。 ダーツ競技は健康な体と豊かな心を育むスポーツとして、年齢、性別に関係なく誰でも気軽にプレーできることから、多くの人々に親しまれてきました。 情操教育の一環として学校教育で行う事の出来る「教育スポーツ」、心身の健全育成を目指した「競技スポーツ」、高齢化社会へ向かっての「生涯スポーツ」として、今の日本に新しい息吹を吹き起こすスポーツとして注目を集めています。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "教育スポーツとしてのダーツは、自律神経の強化、大脳皮質に対する刺激、集中力や持続力の増強、計算機能力向上に加え、マナーやしつけが身につくなど、幅広い機能向上と効用があることから、メンタルな標的競技、情操教育の一環として、中・高等学校でも取り上げられ始めました。また、運動量は決して多くないため幼児から老人までが気軽に楽しめることから、生涯スポーツとしても親しまれています。青年にとってはストレスの解消、障害のある方にとっては身体機能の回復、高齢者にはリハビリテーションとして、身体機能の回復効果や認知症予防効果などが期待されています。そして、コミュニケーションの手段として、レジャー・レクリエーション性のあるスポーツとして、多様化時代の余暇の使い方に役立っています。\nさらにダーツ競技は、心身の総合力を駆使して競技するため、ある一定期間のプラクティスを行い、競技会への参加やリーグ戦などを通し、能力向上を競い合い高める競技スポーツの側面あります。\nこれらの３つ（教育、生涯、競技）のスポーツ区分を兼ね備えているスポーツがダーツです。",
    youtubeId: "OQXqLBMEPbA",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "インディアカ",
    publishedAt: "2022-03-02",
    description:
      "「インディアカ」は羽根の付いた特殊なボール（「インディアカボール」と呼びます。）を手で打ち合う、バレーボールタイプのスポーツです。インディアカボールは、ラケットなどを用いずに直接手で打ち合うことも大きな特徴です。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "ボールに付いている羽根は、小さいボールの滞空時間を長引かせることと、ボールをねらった方向にまっすぐにとばすことができる両面の作用があります。\nしたがって、意図した方向に正確に、ゆっくりと飛ばすことも、速いスピードで飛ばすこともできます。しかも直接手で打つために、よりコントロールしやすく扱いやすいという特長があります。特に羽根によってスピードが緩和されることは、たとえボールに不慣れな初心者であっても、恐怖心を覚えずにプレーに加わることができるという、初心者に優しいスポーツです。\nこのようなボールの持つ特徴によって、インディアカは初心者から熟練者までさまざまなレベルの人たちが、それぞれの技術、能力に応じて、遊技的なゲームから高度な競技にいたるまで、多様なゲームを行うことができるのです。",
    youtubeId: "nCbta6m9bz4",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "カバディ",
    publishedAt: "2022-03-02",
    description:
      "カバディは鬼ごっことドッジボールが融合したような独自のルールを持つスポーツです。\n\r\nインド、パキスタン、バングラデシュなど南アジア諸国で数千年の歴史を持つ、伝統ある国技として親しまれてきたスポーツです。\n\r\n現在では、インド、パキスタン、バングラデシュ、スリランカ、ネパール、イラン、タイ、マレーシア、シンガポール、ブータン、モルジブ、ラオス、インド ネシア、アフガニスタン、トルクメニスタン、キルギスタン、中国、韓国、日本のアジア各国に加え、イングランド、イタリア、ドイツ、カナダ、アメリカ、西インド諸島、オーストラリアと、欧米諸国にも拡がりをみせています。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "紀元前、獣に対し武器を持たずに多彩なテクニックを用いて数人で囲み、声を掛けながら捕らえるという武器を持たずに戦う技術、獣の襲撃から身を守る方法が、やがてスポーツとして成熟し、カバディが生まれました。\n「カバディ」という言葉自体に意味は無く、無心に発声することで平常心へと導き、体と心を一体にするマントラなのです。\nインドの二大叙事詩の一つ「マハーバーラタ（戦記）」に“主人公の息子がクル戦争で七人の敵に囲まれ、突破しようと試みるが力尽きる”という記述があ\nり、それに基づいて、一人のレイダー（攻撃手）と七人のアンティ（守備側）でプレーすることが定められました。\n19世紀にルールの整理が行われ、20世紀にインドのガンジー、ノーベル文学賞受賞者タゴール、ネルー首相などの熱い応援により、全面的な組織作りが行われました。\n1980年に、第１回アジアカバディ選手権大会が開催され、1990年、北京にて開催の第11回アジア競技大会（通称：アジアオリンピック）において正式種目となりました。\n日本国内では、1989年から、全日本カバディ選手権大会を始め、学生選手権大会、西日本大会など年に数回、大きな大会が開催されるようになりました。",
    youtubeId: "yZTHPEL0ioI",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "スポーツウエルネス吹矢",
    publishedAt: "2022-02-07",
    description:
      "スポーツウエルネス吹矢は、健康を目的とした新しい国民的スポーツです。5～10ｍ離れた円形の的をめがけて息を使って矢を放ち、その得点を競うスポーツです。性別・年齢問わず誰でも手軽にでき、ゲーム感覚で楽しみながら健康になれるスポーツとして注目されています。\n\r\n健康効果の秘訣は、腹式呼吸をベースにしたスポーツウエルネス吹矢式呼吸法です。\n\r\n精神集中や血行促進、細胞の活性化に役立ち、内臓の諸器官にもよい影響を与えます。また精神力・集中力が身に付きます。",
    numOfPlayers: "制限なし",
    howLong: "--",
    detail:
      "①「誰でも」性別、年齢問わず楽しめます\n②「いつでも」「どこでも」「手軽に」できます\n③ゲーム感覚で楽しみながらできるスポーツです\n④スポーツウエルネス吹矢式呼吸法による様々な健康効果\n⑤精神力＆集中力を高めます\n⑥様々な世代とのふれあいや仲間づくり\n⑦実力認定や競技会参加による目標ややりがい",
    youtubeId: "ErWrfZ14AvY",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "おもしろスポーツ",
    publishedAt: "2021-06-07",
    description: "ワッキーさんが紹介するおもしろスポーツ",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "UaTo2tpQEnc",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title: "サイコロ21",
    publishedAt: "2021-06-07",
    description:
      "オリジナル！おうちで60秒チャレンジ！\n\r\n「サイコロ21」です。\n\r\n3人それぞれ蹴って出た目の合計が21になる時間を競います。",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "jynFecYGhH8",
  },
  {
    category: "健康スポーツ／ニュースポーツ",
    title:
      "スポーツ庁「運動部活動改革プラン」~スポレク部の創設の取り組み事例紹介~",
    publishedAt: "2020-03-03",
    description:
      "スポーツ庁より委託を受け、運動が苦手な生徒も楽しく取り組める運動部活動を展開します。\n\r\nこの動画は、令和元年度の取り組みの様子をダイジェストにまとめてご紹介しているものです。",
    numOfPlayers: "制限なし",
    howLong: "--",
    youtubeId: "NNb4Bvabm_Q",
  },
];
export default articles;
